### ISSUE TITLE
Some languages do not get their proper emoji.

### ISSUE THREAD

**Issue by RichardKanshen** [centrumek/duolingo-readme-stats#4]
The issue is simple - languages like Norwegian Bokmål do not get a proper emoji. This could be solved with a simple list of images / emojis corresponding to the course titles, instead of relying on an external library.

**Comment by RichardKanshen** [comment]
For context, it looks kind of like this:
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/6870a4d4-f215-48dd-aea9-a9b83f9f887e)

**Comment by RichardKanshen** [comment]
After a couple changes, I got it working with custom svgs for emojis, as well as streak and xp icons
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/dfe605cf-5576-4ae7-bde7-1d3f8aae35a3)

**Comment by centrumek** [comment]
Hi @RichardKanshen , wow thank you for this PR I'll review it very soon :)

**Comment by RichardKanshen** [comment]
After some more tinkering, I also got "from Language" text working, which shows the flag of the base language. Can be disabled for English with SHOW_FROM_ENGLISH option in YAML.
With English shown:
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/2ee634e6-214a-4947-bd82-ac076bf9f146)
Without English Shown:
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/f0936d05-e77b-4c2f-8e68-648644a70c3e)

**Comment by RichardKanshen** [comment]
Another thing - Added leagues! 
They require two user cookies to be passed via GitHub Secrets, but they finally work!
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/9ba05111-110d-49a9-bd45-885146331a11)

**Comment by RichardKanshen** [comment]
Also, since I added the cookies option, I also added XP earned since last leaderboard reset.
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/9ea0efe1-0cc2-4b47-a9e9-efde2224120c)

**Comment by RichardKanshen** [comment]
Also added the inactive streak icon (updates based on the user timezone)

day 129 before streak extension:
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/3a97744e-53ad-43d9-9a1e-aa373f2acbd4)
day 129 after streak extension:
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/822edb49-6c36-4134-be53-edb0fc83b568)
day 130 before streak extension: 
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/351ba842-f85a-4a60-b2bd-48b8d3aa6372)

**Comment by RichardKanshen** [comment]
Added Streak Freeze icon if the streak has been frozen, too!
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/b4e41f2e-0493-4398-b22f-f057c0020133)

**Comment by RichardKanshen** [comment]
Added the option to show the timezone in which Streak is counted.
![image](https://github.com/centrumek/duolingo-readme-stats/assets/73738591/5b029a09-8586-4f05-a952-21418c588f53)

**Comment by centrumek** [comment]
Hi @RichardKanshen, I apologise for my long review, I'll try to make it this week :).

Wow, what's an update till that time

**Comment by centrumek** [comment]
Thanks @RichardKanshen I've merged your changes.

I'll make a a few adjustments, like refactor a bit of code and link to `centrumek...` assets yet and release version `2.0.0` :)
